export const QUOTE_LIST_HAVE_ERROR = 'QUOTE_LIST_HAVE_ERROR';
export const QUOTE_LIST_ARE_LOADING = 'QUOTE_LIST_ARE_LOADING';
export const QUOTE_LIST_FETCH_DATA_SUCCESS = 'QUOTE_LIST_FETCH_DATA_SUCCESS';

export const QUOTE_DETAILS_HAVE_ERROR = 'QUOTE_DETAILS_HAVE_ERROR';
export const QUOTE_DETAILS_ARE_LOADING = 'QUOTE_DETAILS_ARE_LOADING';
export const QUOTE_DETAILS_FETCH_DATA_SUCCESS = 'QUOTE_DETAILS_FETCH_DATA_SUCCESS';

export const QUOTE_START_HAVE_ERROR = 'QUOTE_START_HAVE_ERROR';
export const QUOTE_START_ARE_LOADING = 'QUOTE_START_ARE_LOADING';
export const QUOTE_START_FETCH_DATA_SUCCESS = 'QUOTE_START_FETCH_DATA_SUCCESS';
export const QUOTE_START_UPDATE_DATA_SUCCESS = 'QUOTE_START_UPDATE_DATA_SUCCESS';

